version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - test-network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
